
global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'examlpe'

# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.
scrape_configs:


  - job_name: "prometheus"  
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "telegraf"
    static_configs:
      - targets: ["telegraf:9273"]

  # - job_name: "node"
  #   static_configs:
  #     - targets: ["localhost:9100"]

